export { default as Home } from "../pages/Home";
export { default as Login } from "../pages/auth/Login";
export { default as Register } from "../pages/auth/Register";
export { default as Reset } from "../pages/auth/Reset";
export { default as About } from "../pages/About";
export { default as Contact } from "../pages/Contact";
export { default as Shop } from "../pages/Shop";
export { default as Admin } from "../pages/Admin";
export { default as ProductDetails } from "../components/product/ProductDetails";
